name: Build and share Docker Image to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-share:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get short commit hash
        id: get_version
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "Commit hash: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:latest

  deploy-to-ec2:
    needs: build-and-share
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2SSH }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2IP }}
          username: ubuntu
          key: ${{ secrets.EC2SSH }}
          script: |
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
            echo "DOCKERHUB_REPO_NAME=${{ secrets.DOCKERHUB_REPO_NAME }}" >> .env
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            cat .env
            ssh -o StrictHostKeyChecking=no -i private_key ec2-user@${HOSTNAME} 
            cd /home/ubuntu/django-ecom-test-deployment
            echo "Pulling latest changes"
            git pull
            echo "Pulling latest Docker images"
            docker compose pull
            echo "Bringing down existing containers"
            docker compose down
            echo "Starting new containers"
            docker compose up -d
            
  notify-retrace:
      needs: deploy-to-ec2
      runs-on: ubuntu-latest
      
      steps:
        - name: Notify Retrace of Deployment
          run: | 
                curl -X POST https://api.stackify.net/api/v1/deployments/complete -H "Content-Type: application/json" -H "authorization: ApiKey ${{ secrets.API_KEY_STACKIFY }}" \
                -d "{
                \"EnvironmentName\": \"Production\",
                \"AppName\": \"DJEcommerce_Ec2\",
                \"DeployedBy\": \"GitHub Actions\",
                \"Version\": \"v1.1\",
                \"Branch\": \"master\"
                }" -v
